# Generated by Django 6.1 on 2026-08-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device Approval', 'verbose_name_plural': 'Device Approvals'},
        ),
    ]
