"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&(u&v&@^(f)uy1&r1y-+4(u43^!$zj%7c(9)103h*6!4fa=u7g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "allmusic-backend.onrender.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    "accounts",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


CORS_ALLOWED_ORIGINS = [
    "https://allmusic45.netlify.app",

    "http://127.0.0.1:5500",
    "http://localhost:5500",

    "http://127.0.0.1:5501",
    "http://localhost:5501",
]

CSRF_TRUSTED_ORIGINS = [
    "https://allmusic45.netlify.app",

    "http://127.0.0.1:5500",
    "http://localhost:5500",

    "http://127.0.0.1:5501",
    "http://localhost:5501",
]

JAZZMIN_SETTINGS = {

    "site_title": "All Music Admin",

    "site_header": "All Music",

    "site_brand": "All Music",

    "welcome_sign": "Welcome to All Music Admin",

    "copyright": "All Music",

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_models": [],

    "hide_apps": [],

    "order_with_respect_to": [
        "accounts",
        "auth",
    ],

    "icons": {
        "accounts.Device": "fas fa-mobile-alt",
        "auth.User": "fas fa-users",
        "auth.Group": "fas fa-user-shield",
    },

    "custom_links": {
        "accounts": [
            {
                "name": "Device Approvals",
                "url": "admin:accounts_device_changelist",
                "icon": "fas fa-check-circle",
            },
        ],
    },

    "topmenu_links": [
        {
            "name": "Dashboard",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "Users",
            "url": "admin:auth_user_changelist",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "Devices",
            "url": "admin:accounts_device_changelist",
            "permissions": ["accounts.view_device"],
        },
    ],

    "usermenu_links": [
        {
            "name": "All Music Website",
            "url": "https://allmusic45.netlify.app/",
            
            "new_window": True,
        },
    ],

    "related_modal_active": True,

    "show_ui_builder": True,
}
JAZZMIN_UI_TWEAKS = {
    "theme": "default",

    "default_theme_mode": "light",

    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    "brand_colour": "navbar-dark",
    "accent": "accent-primary",

    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,

    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

JAZZMIN_SETTINGS = {

    "site_title": "Spotify Music Admin",
    "site_header": "Spotify",
    "site_brand": "Spotify Music",

    "welcome_sign": "Welcome to Spotify Music Admin",
    "copyright": "Spotify Music",

    "site_icon": "favicon.png",
    "site_logo": "favicon.png",

    "custom_css": "admin/css/custom.css",

    "show_sidebar": True,
    "navigation_expanded": True,
}