# Generated by Django 6.1 on 2026-08-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_songsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsuggestion',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
